Section "InputClass"
    Identifier "MacBook touchpad defaults"
    MatchIsTouchpad "on"
    Driver "libinput"
    Option "Tapping" "on"
    Option "NaturalScrolling" "true"
    Option "DisableWhileTyping" "on"
    Option "ClickMethod" "clickfinger"
EndSection
